### ISSUE TITLE
Update readme for Webpack 2

### ISSUE THREAD

**Issue by kostasmanionis** [webpack-contrib/jshint-loader#30]
We should update our README to reflect the changes made to the API in webpack 2. Here's an example of a [new README from less-loader](https://github.com/webpack/less-loader/pull/119/files).

**Comment by josfaber** [comment]
Yes please. I cannot get it to work with webpack 2 :(

**Comment by kostasmanionis** [comment]
@josfaber check out this PR https://github.com/webpack-contrib/jshint-loader/pull/32. It has the updated readme and example.

**Comment by josfaber** [comment]
Thanks for that!
Sadly, this give me the following error:

> /Users/jos/workspace/egohub/webpack.config.js:34
>         new webpack.LoaderOptionsPlugin({
>             ^
> 
> ReferenceError: webpack is not defined
>     at Object.<anonymous> (/Users/jos/workspace/egohub/webpack.config.js:34:13)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at requireConfig (/Users/jos/workspace/egohub/node_modules/webpack/bin/convert-argv.js:96:18)
>     at /Users/jos/workspace/egohub/node_modules/webpack/bin/convert-argv.js:109:17

I've had webpack installed globally, and after this error locally.
My npm dependencies:

>   "dependencies": {
>     "babel-core": "6.22.1",
>     "babel-loader": "6.2.10",
>     "babel-preset-es2015": "6.22.0",
>     "jquery": "3.1.1",
>     "jshint": "2.9.4",
>     "jshint-loader": "0.8.3",
>     "node-sass": "^3.8.0",
>     "nodemon": "^1.10.2",
>     "webpack": "2.2.1"
>   }

Bugging webpack.config.js:

>     module: {
>         rules: [
>             {
>                 test: /\.js$/,
>                 exclude: /node_modules/,
>                 enforce: "pre",
>                 loader: "jshint-loader"
>             },
>             {
>               test: /\.js$/,
>               loader: 'babel-loader',
>               options: {
>                 presets: ['es2015']
>               }
>             }
>         ]
>     },
> 
>     plugins: [
>         new webpack.LoaderOptionsPlugin({
>             // http://www.jshint.com/docs/options/
>             unused: false,
>             asi: true,
>             eqeqeq: true,
>             browser:true,
>             node:true,
>             globals:{
>               jQuery:false,
>               window:false
>             }
>         })
>     ]

The one I posted [here above](https://github.com/webpack-contrib/jshint-loader/issues/30#issuecomment-276704295) does work..

**Comment by kostasmanionis** [comment]
@josfaber you probably need to require webpack in your `webpack.config.js` file, i.e. 

```
const webpack = require('webpack');
```

Your example should work too, though you probably shouldn't define the loader twice.

```
'jshint-loader',
{ loader: "jshint-loader", options: { camelcase: true, emitErrors: false, failOnHint: false } }
```

Should be enough to just have

```
{ loader: "jshint-loader", options: { camelcase: true, emitErrors: false, failOnHint: false } }
```

**Comment by josfaber** [comment]
Man, I should have thought about that one myself..  * shame * Thanks!

**Comment by kostasmanionis** [comment]
Hmmmmmmm does it work if you pass the options like this?

```
{ 
    loader: "jshint-loader", 
    options: { 
        camelcase: true, 
        emitErrors: false, 
        failOnHint: false 
    } 
}
```

I'm starting to think that `jshint-loader` doesn't need `webpack.LoaderOptionsPlugin`...

**Comment by Rodrigoleon** [comment]
@josfaber `jshint-loader` should not need the `webpack.LoaderOptionsPlugin`. You can try checking out [my repo](https://github.com/Rodrigoleon/Webpack-Launchpad) if you need some help configuring JSHint with additional plugins and loaders. [This video](https://youtu.be/ZlPqkxohjcM?list=PLpPnRKq7eNW2_dy8Re4lyByThMtTAhw5Q) should also help some (towards the very end).

**Comment by donkeybrains** [comment]
Webpack/node, same issue today, even with using a .jshintrc file.

The options dont work even if I add the options as shown here.

In the index.js of jshint the this.options is undefined, hence the exception.

**Comment by felipealfonsog** [comment]
Under my perspective, in Linux (Debian in my case) webpack is so tricky .... don't not why ...
