### ISSUE TITLE
Does not work on Node < 4.0.0

### ISSUE THREAD

**Issue by rictorres** [webpack-contrib/jshint-loader#39]
**What kind of issue are you submitting?**
* **Bug Report**

* **jshint-loader version** 0.8.4

https://github.com/webpack-contrib/jshint-loader/pull/37 updated `loader-utils` to `^1.0.2`. However, from `v0.2.17` (https://github.com/webpack/loader-utils/commit/4130dff5d46376b1f7b46162893e0a6e7547b27a) `loader-utils` started using ES6 features from `node >= 4.0.0`.

```
ERROR in /node_modules/jshint-loader/node_modules/loader-utils/lib/parseQuery.js:24
	queryArgs.forEach(arg => {
	                      ^^
Unexpected token =>
```

I believe this is a breaking change for everyone using Node < 4 (including `iojs`).

**Comment by d3viant0ne** [comment]
Webpack itself does not support node < 4.3

**Comment by rictorres** [comment]
alright, then. i'm gonna stick with `0.8.3` for now. thanks

**Comment by d3viant0ne** [comment]
@rictorres - Something to keep in the back of your mind. The move to default es6 module output has begun, it is something you will see more over the coming months & Node v8 LTS isn't too far off.

It's time to get off the older node / IO.js versions & Webpack 1.x. That said, you are in luck! The [webpack-cli team](https://github.com/webpack/webpack-cli) is looking for people to test their migration tool which may provide a simplified migration to `webpack@latest` for your projects.

**Comment by rictorres** [comment]
@d3viant0ne I understand that :)
Most of my personal projects are using Node > 7 already, however in this specific case, updating from `iojs-2.5.0` is breaking a lot of stuff and I just don't have enough time at the moment to inspect it further :'(

Thanks for the heads up though and keep up the awesome work! 👍
