### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.  - configuration.output.path: The provided value "./build/" is not an absolute path!    -> The output directory as **absolute path** (required).

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/jshint-loader#57]
My webpack.config.js file

module.exports={
    entry:['./app/index.js'],
    output:{
        path:'./build/',
        filename:'bundle.js'
 }
} 

And getting this error

C:\Users\Hafiz Musaddiq Babar\Desktop\es6>npm run build

> es6@1.0.0 build C:\Users\Hafiz Musaddiq Babar\Desktop\es6
> webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./build/" is not an absolute path!
   -> The output directory as **absolute path** (required).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es6@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hafiz Musaddiq Babar\AppData\Roaming\npm-cache\_logs\2018-09-12T02_45_23_508Z-debug.log

**Comment by michael-ciniawsky** [comment]
**`webpack.config.js`**
```diff
+ const path = require('path')

module.exports = {
  entry: [ './app/index.js' ],
  output:{
-   path: './build/',
+   path: path.resolve(__dirname, 'build'),
    filename: 'bundle.js'
  }
}
```
